// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SweetSavory.Models;

namespace SweetSavory.Migrations
{
    [DbContext(typeof(SweetSavoryContext))]
    [Migration("20190731215748_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SweetSavory.Models.Flavors", b =>
                {
                    b.Property<int>("FlavorsId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("FlavorsId");

                    b.ToTable("Flavors");
                });

            modelBuilder.Entity("SweetSavory.Models.FlavorsTreat", b =>
                {
                    b.Property<int>("FlavorsTreatId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("FlavorsId");

                    b.Property<int>("TreatId");

                    b.HasKey("FlavorsTreatId");

                    b.HasIndex("FlavorsId");

                    b.HasIndex("TreatId");

                    b.ToTable("FlavorsTreat");
                });

            modelBuilder.Entity("SweetSavory.Models.Treat", b =>
                {
                    b.Property<int>("TreatId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.HasKey("TreatId");

                    b.ToTable("Treats");
                });

            modelBuilder.Entity("SweetSavory.Models.FlavorsTreat", b =>
                {
                    b.HasOne("SweetSavory.Models.Flavors", "Flavors")
                        .WithMany("Treats")
                        .HasForeignKey("FlavorsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SweetSavory.Models.Treat", "Treat")
                        .WithMany("Flavors")
                        .HasForeignKey("TreatId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
